services:
  makani:
    image: makani:latest-25.11-x86_64
    user: "${DOCKER_UID:-nobody}:${DOCKER_GID:-nogroup}"
    network_mode: host
    ipc: host
    environment:
      - NUMBA_CACHE_DIR=/data/cache/numba
      - TRITON_CACHE_DIR=/data/cache/triton
      - WANDB_DATA_DIR=/data/cache/wandb
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - CUDA_MODULE_LOADING=LAZY
      - NETRC=/netrc
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - .:/opt/makani
      - /data:/data
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /data/cache/home_cache:/home/${USER}/.cache
      - ~/.netrc:/netrc:ro
    working_dir: /opt/makani
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
